project:
  type: website
  output-dir: docs
  
website:
  title: "Dados da Fundação Meridional"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/NatanK21/site_fundacao
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: pulse
    toc: true

editor: source

